feature: Balance component
MarcinBolt/Wallet-App pull request #31
Opened 2023-09-24 17:28 UTC by Julia-Kaim

nie mam pewności, jak używać variables w mui, potrzebuję przykładu od kogoś innego i wtedy pozmieniam

2023-09-25 10:46 UTC, MarikaGK requested changes
Komponent do drobnych poprawek stylizacyjnych
Usuń operacje dotyczące balance, są w złych miejscach, wystarczy komponent, logiką zajmiemy się później

2023-09-25 10:46 UTC, MarikaGK commented on src/App.jsx
> +// const Balance = lazy(() => import('./components/Balance/Balance.jsx'));
Usuń komentarze z App

2023-09-25 10:46 UTC, MarikaGK commented on src/components/Balance/Balance.jsx
> +// import css from '../../utils/css-variables.css';
Usuń komentarze (wiem, że to do zmiennych, ale póki co import niepotrzebny)

2023-09-25 10:46 UTC, MarikaGK commented on src/components/Balance/Balance.jsx
> +        height: 'auto',
height: 80

2023-09-25 10:46 UTC, MarikaGK commented on src/components/Balance/Balance.jsx
> +        marginBottom: 32,
Nie ma uzasadnienia margin w elemencie zewnętrznym, położenie wystylizuje nadrzędny

2023-09-25 10:46 UTC, MarikaGK commented on src/components/Balance/Balance.jsx
> +        fontSize: 12,
font-size nie potrzebny
za to przydałby się padding, żeby ustawić elementy w środku:
padding: '8px 32px 11px'
i od tabletu '8px 40px 11px'

2023-09-25 10:46 UTC, MarikaGK commented on src/components/Balance/Balance.jsx
> +          fontWeight: 'bold',
dubluje się fontWeight i nadpisuje prawidłowy

2023-09-25 10:46 UTC, MarikaGK commented on src/components/Balance/Balance.jsx
> +          padding: '10px',
padding niepotrzebny

2023-09-25 10:46 UTC, MarikaGK commented on src/components/Balance/Balance.jsx
> +          fontWeight: 400,
fontWeight: 700

2023-09-25 10:46 UTC, MarikaGK commented on src/components/Balance/Balance.jsx
> +          fontWeight: 'bold',
Zdublowany fontWeight

2023-09-25 10:46 UTC, MarikaGK commented on src/components/Balance/Balance.jsx
> +          paddingLeft: '15px',
bez paddingu

2023-09-25 10:46 UTC, MarikaGK commented on src/redux/auth/auth.slice.js
> +export const selectUserBalance = state => state.auth.user.balance;
selektory powinny być w pliku z selectorami, później się tym zajmiemy

2023-09-25 10:46 UTC, MarikaGK commented on src/redux/store.js
> +import { configureStore, createSelector } from '@reduxjs/toolkit';
Musisz pousuwać te wszystkie selectory

2023-09-25 10:46 UTC, MarikaGK commented on src/redux/store.js
> +);
w store nie robi się reducerów

2023-09-25 10:46 UTC, MarikaGK commented on src/redux/transactions/transactions.slice.js
> +export const selectUserBalanceAfter = state => state.transactions.balance;
to też usuń

2023-09-25 13:38 UTC, MarikaGK requested changes

2023-09-25 13:38 UTC, MarikaGK commented on src/App.jsx
> +        {/* <Route exact path={`/`} element={<PublicRoute component={<Balance />} />} /> */}
Jeszcze tu zakomentowany kod do usunięcia :)

2023-09-25 13:38 UTC, MarikaGK commented on src/redux/auth/auth.slice.js
> +export const selectUserBalance = state => state.auth.user.balance;
Tu jeszcze się jeden gagatek zaplątał

2023-09-26 09:49 UTC, MarikaGK requested changes
Jeszcze drobne niezgodności

2023-09-26 09:49 UTC, MarikaGK commented on src/App.jsx
> +        <Route exact path={`/`} element={<PublicRoute component={<Balance />} />} />
W Route nie będzie Balance (będzie importowany na dashboard)

2023-09-26 09:49 UTC, MarikaGK commented on src/components/Balance/Balance.module.css
> +}
Nie działa RWD, mamy tu dwóch winowajców:
W zapytaniach medialnych brakuje screen (@media screen and (....) {})
Jest podana klasa Balance, a powinna być BalanceContainer

2023-09-26 09:49 UTC, MarikaGK commented on src/components/Balance/Balance.module.css
> +  font-size: 30;
font-size: 30px; (brakuje px)

2023-09-29 20:20 UTC, MarikaGK requested changes

2023-09-29 20:20 UTC, MarikaGK commented on src/components/Balance/Balance.module.css
> +@media screen and (min-width: 780px) {
768px

2023-09-29 20:20 UTC, MarikaGK commented on src/components/Balance/Balance.module.css
> +@media screen and (min-width: 1200px) {
min 1280px

2023-09-29 20:20 UTC, MarikaGK commented on src/components/Balance/Balance.module.css
> +    width: 360px;
336px

2023-09-29 20:20 UTC, MarikaGK commented on src/components/Dashboard/Dashboard.jsx
Komponent do usunięcia, teraz jest jako page

2023-09-29 20:23 UTC, Julia-Kaim commented on src/components/Balance/Balance.module.css
> +@media screen and (min-width: 1200px) {
done

2023-09-29 20:23 UTC, Julia-Kaim commented on src/components/Balance/Balance.module.css
> +    width: 360px;
done

2023-09-29 20:24 UTC, Julia-Kaim commented on src/components/Dashboard/Dashboard.jsx
nie widzę takiego u siebie

2023-10-01 12:38 UTC, MarcinBolt approved these changes
Super Mari, dzięki że to ogarnęłaś.
Chcesz mieć coś zrobione, zrób to sam/a :)

2023-10-01 12:38 UTC, merged