Jonasz Chudobski navigation-buttons
MarcinBolt/Wallet-App pull request #38
Opened 2023-09-25 19:43 UTC by JonaszChudobski

Hej! Zrobiłem guziczki w wersji na mobilkę i na tablet/desktop (w obu ostatnich wersjach są takie same style). 
Ponieważ są to guziki nawigacyjne dodałem również właściwe routy, na które mają przekierowywać, przy czym content jest dodany jako outlet w komponencie Dashboard, dlatego pojawił się komponent Home obok innych.
Mam nadzieję, że pull jest na miejscu i że szanuję Wasz czas i nie będziecie zionąć nienawiścią :D

2023-09-26 14:30 UTC, MarikaGK commented
Jonaszu, szanuj nasz czas i merguj do dev, nie do main XD

PS. Już zmieniam

2023-09-26 15:26 UTC, MarikaGK requested changes
Poprawki według komentarzy
Brakuje mi czegoś na hover, np. sam ten box shadow z active?

2023-09-26 15:26 UTC, MarikaGK commented on src/components/Navigation/Navigation.jsx
> +      <NavLink className={css.dollar__link} to="statistics"></NavLink>
Czy grupa trzech elementów nie powinna być listą?
nie będzie routy home, tylko transactions, ani diagram tylko staistics, a statistic dałeś do currency

2023-09-26 15:26 UTC, MarikaGK commented on src/components/Navigation/Navigation.module.css
> +    padding: 40px 0 28px 32px;
no padding, please!

2023-09-26 15:26 UTC, MarikaGK commented on src/components/Navigation/Navigation.module.css
> +    padding: 12px;
bez paddingu, odstępy nada komponent nadrzędny
A skoro korzystasz z fleksa, odsuń od siebie elementy gap: 32px dla mobilki albo zostaw space-evenly, ale
nadaj jakąś maksymalną szerokość, np 280px dla mobilki, bo balance ma właśnie 280, nie chcemy, żeby nam się guziczki brzydko rozjechały na szerszym ekranie

2023-09-26 15:26 UTC, MarikaGK commented on package.json
> -    "joi": "^17.10.2",
Zrób update z dev, nie chcemy usunąć joi

2023-09-26 15:26 UTC, MarikaGK commented on src/components/Home/Home.jsx
Niepotrzebny komponent, wszystko będzie w Dashboard

2023-09-26 15:26 UTC, MarikaGK commented on src/components/Navigation/Navigation.module.css
> +    padding: 40px 0 28px 32px;
no padding

2023-09-26 15:26 UTC, MarikaGK commented on src/components/Navigation/Navigation.module.css
> +    margin-left: 20px;
margin-left: 23px

2023-09-26 19:43 UTC, JonaszChudobski commented on src/components/Navigation/Navigation.jsx
> +      <NavLink className={css.dollar__link} to="statistics"></NavLink>
Gdyby odpowiedź zależała ode mnie, powiedziałbym nie :) Ale pewnie w dokumentacji htmla jest, że powinna, więc powiem: oczywiście, jak najbardziej!

2023-09-26 19:43 UTC, JonaszChudobski commented on src/components/Navigation/Navigation.module.css
> +    padding: 40px 0 28px 32px;
Here you are!

2023-09-26 19:44 UTC, JonaszChudobski commented on src/components/Navigation/Navigation.module.css
> +    padding: 12px;
Aye, aye, ma'am :)

2023-09-26 19:44 UTC, JonaszChudobski commented on package.json
> -    "joi": "^17.10.2",
Absolutnie nie chcemy, daje nam tyle radości :P

2023-09-26 19:44 UTC, JonaszChudobski commented on src/components/Home/Home.jsx
Wypier*łem w kosmos!

2023-09-26 19:44 UTC, JonaszChudobski commented on src/components/Navigation/Navigation.module.css
> +    padding: 40px 0 28px 32px;
Nie ma i nie będzie!

2023-09-26 19:45 UTC, JonaszChudobski commented on src/components/Navigation/Navigation.module.css
> +    margin-left: 20px;
Zmienione.

2023-09-26 21:21 UTC, MarikaGK approved these changes
Brawo! :)

2023-09-28 09:21 UTC, MarikaGK approved these changes
Jest ok

2023-09-28 09:21 UTC, merged