add images, icons and add component modalAddTransaction
MarcinBolt/Wallet-App pull request #5
Opened 2023-09-20 14:35 UTC by MaciejKociemski

w asset
dodalem folder icons,
dodalem images,
dodalem icons,

dodalem komponenty:
modalAddTransaction a w nim modalAddTransaction.jsx oraz .css z wykorzystaniem zmiennych juz dodanych do projektu,
oraz modalLogout a w nim modalLogout.jsx (jeszcze bez kodu)

dodalem do utils breakpointsy dla mobilki, tableta i desktopa,

do selectorow dodalem selector potrzebny do dostepu do kategorii transakcji ktorej uzywam w modalAddTransaction

do redux/transactions/operations dodalem fetchCategories ktorego uzywam w modalAddTransaction do pobrania dostepnych kategorii transakcji , tak aby user mogl wybrac odpowiednia kategorie podczas dodawania transakcji . 

//(w modalAddTransaction zostawilem jeszcze komentarz o uzyciu TextField z @mui bo lokalnie mam swoją wersję bez mui). Oczywiście na koniec komentarze będa skasowane//

2023-09-20 17:10 UTC, MarcinBolt requested changes
Do małej poprawy. Więcej w komentarzach.

2023-09-20 17:10 UTC, MarcinBolt commented on src/components/modalAddTransaction/modalAddTransaction.css
> +@media (min-width: var(--TabletWidth)) {
Fajnie, że dodałeś oddzielnie swoje breakpointy dla mediów. Jednak, czy widziałeś plik /src/utils/constants.js ? Tam również są zawarte w obiekcie mediaQueries.

2023-09-20 17:10 UTC, MarcinBolt commented on src/assets/icons/wave-mobile (1).svg
Tu są dwa pliki o prawie takiej samej nazwie, tylko ten na dodaną (1) na końcu - jakby kopia?

2023-09-20 17:10 UTC, MarcinBolt commented on src/assets/images/registration/register-tablet@2x.png
Super Maciej, że ogarnąłeś wszystkie obrazy i ikony! Ogrom pracy, SZACUNEK! Dziękuję!

2023-09-20 17:10 UTC, MarcinBolt commented on src/components/modalAddTransaction/modalAddTransaction.css
Nazwy komponentów zaczynamy wielką literą, więc trzeba zmienić, nazwy plików: .jsx i .css oraz folderu.

2023-09-20 17:10 UTC, MarcinBolt commented on src/components/modalLogout/modalLogout.jsx
Ten nazwa pliku oraz folderu, w którym jest zawarty również trzeba zmienić.

2023-09-20 17:12 UTC, MaciejKociemski commented on src/assets/icons/wave-mobile (1).svg
jeden do usuniecia, dwa razy wrzucilem

2023-09-20 20:22 UTC, MarcinBolt reviewed
Już nie wiem czy zapisałem ten CR, dodam jako comment.

2023-09-21 09:10 UTC, MaciejKociemski commented on src/components/modalAddTransaction/modalAddTransaction.css
> +@media (min-width: var(--TabletWidth)) {
zostawię breakpointsy ktore dodalem,  mediaQueries z zapisami z szablonami literałów ${} nie są obsługiwane w plikach CSS - taki mam błąd po zastosowaniu @media (min-width: ${mediaQueries.tablet}) {}
 Do wyboru albo uzyc konkretnych wartości szerokości ekranu wewnątrz deklaracji @media albo skorzystac z breakpointsów

2023-09-21 10:42 UTC, MaciejKociemski commented on src/components/modalAddTransaction/modalAddTransaction.css
done

2023-09-21 10:42 UTC, MaciejKociemski commented on src/components/modalLogout/modalLogout.jsx
done

2023-09-23 10:18 UTC, MaciejKociemski commented
Usunąłem z tej gałęzi ModalAddTransaction i ModalLogout, zostawiłem obrazki i ikony.

2023-09-23 17:23 UTC, MaciejKociemski commented
zamykam, na nowo bedzie w osobnym branchu

2023-09-23 17:23 UTC, closed without merging